name: SafeTrade CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: TempPassword123!
          MYSQL_DATABASE: safetrade_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.0'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install backend dependencies
      run: |
        cd packages/backend
        npm ci
    
    - name: Wait for MySQL to be ready
      run: |
        until docker exec $(docker ps -q --filter ancestor=mysql:8.0) mysqladmin ping --silent; do
          echo 'Waiting for MySQL to be available...'
          sleep 1
        done
        echo 'MySQL is available'

    - name: Create backend test env
      run: |
        cd packages/backend
        cat > .env << EOF
        NODE_ENV=test
        DB_HOST=localhost
        DB_PORT=3306
        DB_NAME=safetrade_test
        DB_USER=root
        DB_PASSWORD=TempPassword123!
        JWT_SECRET=test_jwt_secret_key_12345
        JWT_REFRESH_SECRET=test_refresh_secret_key_12345
        EOF
    
    - name: Run backend linting
      run: |
        cd packages/backend
        npm run lint
    
    - name: Run backend tests
      run: |
        cd packages/backend
        npm run test
    
    - name: Run backend e2e tests
      run: |
        cd packages/backend
        npm run test:e2e

  test-admin-portal:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.0'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install admin portal dependencies
      run: |
        cd packages/admin-portal
        npm ci
    
    - name: Create admin portal test env
      run: |
        cd packages/admin-portal
        cat > .env.local << EOF
        NEXT_PUBLIC_API_URL=http://localhost:3000/api/v1
        NODE_ENV=test
        JWT_SECRET=test_jwt_secret_key_12345
        EOF
    
    - name: Run admin portal linting
      run: |
        cd packages/admin-portal
        npm run lint
    
    - name: Run admin portal type checking
      run: |
        cd packages/admin-portal
        npm run type-check
    
    - name: Build admin portal
      run: |
        cd packages/admin-portal
        npm run build

  build:
    runs-on: ubuntu-latest
    needs: [test-backend, test-admin-portal]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.0'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build all packages
      run: npm run build
    
    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          packages/backend/dist/
          packages/admin-portal/.next/